import { ArrowUpRight, BadgeIndianRupee, Boxes, CheckCircle2, Leaf, Plus, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import AppShell from '../../components/layout/AppShell';
import StatCard from '../../components/common/StatCard';
import Badge from '../../components/common/Badge';
import { useRaw } from '../../store/RawStore';

export default function DonorDashboard() {
  const { currentUser, listings, offers, impact } = useRaw();
  const activeListings = listings.filter((l) => l.status === 'ACTIVE');
  const pendingOffers = offers.filter((o) => o.status === 'PENDING');
  const greeting = new Date().getHours() < 12 ? 'Good morning' : new Date().getHours() < 17 ? 'Good afternoon' : 'Good evening';
  return <AppShell><div className="flex flex-col gap-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-teal-700">{greeting}, {currentUser.name.split(' ')[0]}</p><h1 className="mt-1 text-3xl font-black tracking-tight">Your RAW dashboard</h1><p className="mt-2 text-sm text-slate-500">Keep surplus moving and turn unused inventory into value.</p></div><Link to="/donor/listings/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> List RAW</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active listings" value={String(activeListings.length)} hint={activeListings.length ? `${activeListings.length} in circulation` : 'No active listings'} icon={Boxes}/><StatCard label="Pending offers" value={String(pendingOffers.length)} hint={pendingOffers.length ? `${pendingOffers.length} awaiting response` : 'None pending'} icon={ArrowUpRight}/><StatCard label="Value recovered" value={`₹${impact.valueRecovered.toLocaleString()}`} hint="Across completed exchanges" icon={BadgeIndianRupee}/><StatCard label="Material recovered" value={`${(impact.materialRecovered / 1000).toFixed(2)} t`} hint={`Across ${impact.successfulTransactions} exchanges`} icon={Leaf}/></div>
    <div className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Incoming offers</h2><p className="text-sm text-slate-500">Offers from seekers for your active RAW.</p></div><Link to="/donor/offers" className="text-sm font-semibold text-teal-700">View all</Link></div><div className="mt-5 space-y-3">{offers.slice(0,5).map((o) => { const listing = listings.find((item) => item.id === o.listingId); return <div key={o.id} className="flex items-center gap-4 rounded-xl border border-slate-100 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-teal-50 text-teal-700"><Sparkles className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="font-semibold">{o.quantity} {listing?.unit ?? 'units'} of {listing?.material ?? 'material'}</p><p className="text-sm text-slate-500">Offer ₹{o.price.toLocaleString()} · {o.message}</p></div><Badge tone={o.status === 'PENDING' ? 'warning' : 'brand'}>{o.status}</Badge></div>; })}{offers.length === 0 && <p className="py-4 text-center text-sm text-slate-400">No offers yet — list RAW to get started.</p>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-300">Your impact</p><div className="mt-3 text-3xl font-black">{impact.materialRecovered.toLocaleString()} kg</div><p className="mt-1 text-sm text-slate-300">material kept in circulation</p><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-400">Successful transactions</span><span className="font-semibold">{impact.successfulTransactions}</span></div><div className="flex justify-between"><span className="text-slate-400">Reuse cycles</span><span className="font-semibold">{impact.reuseCycles}</span></div><div className="flex justify-between"><span className="text-slate-400">Waste avoided</span><span className="font-semibold">{impact.estimatedWasteAvoided} kg*</span></div></div><div className="mt-6 flex items-center gap-2 text-xs text-slate-400"><CheckCircle2 className="h-4 w-4 text-teal-300" /> Impact figures are estimates.</div></section>
    </div>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="p-5 pb-3"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Your RAW inventory</p><h2 className="mt-1 text-xl font-black">Keep reusable materials visible</h2></div><div className="grid gap-4 p-5 pt-2 md:grid-cols-3">{activeListings.slice(0,3).map((item) => <div key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="aspect-[16/9] overflow-hidden bg-slate-100"><img src={item.image} alt={item.title} className="h-full w-full object-cover object-center" /></div><div className="p-4"><div className="flex items-center justify-between"><div className="text-xs font-semibold uppercase tracking-wider text-teal-700">{item.category}</div><Badge tone={item.status === 'ACTIVE' ? 'success' : 'neutral'}>{item.status}</Badge></div><h3 className="mt-2 line-clamp-2 text-sm font-bold">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.quantity} {item.unit} · {item.distanceKm} km</p><div className="mt-4 flex items-center justify-between"><span className="text-base font-black">{item.price ? `₹${item.price}/${item.unit === 'kg' ? 'kg' : 'unit'}` : 'Free'}</span><Link to={`/donor/listings/${item.id}`} className="text-xs font-semibold text-teal-700">Manage</Link></div></div></div>)}{activeListings.length === 0 && <p className="py-8 text-center text-sm text-slate-400 md:col-span-3">No active listings yet.</p>}</div></div>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="relative min-h-72 overflow-hidden"><img src="/raw-materials-dark.svg" alt="Reusable and recoverable raw materials" className="h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/75 via-slate-950/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">Keep resources moving</p><p className="mt-2 max-w-md text-lg font-black">From surplus to a useful next life.</p><p className="mt-1 text-sm text-slate-200">Every completed exchange extends the value already embedded in a material.</p></div></div></div>
    </section>
  </div></AppShell>;
}
