import { ArrowRight, Bot, CheckCircle2, MapPin, Recycle, ShieldCheck, Sparkles, Store, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Landing() {
  return <div className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-slate-950"><Recycle className="h-5 w-5" /></div><span className="text-xl font-black tracking-tight">RAW</span></div><div className="flex items-center gap-3"><Link to="/auth/login" className="rounded-xl px-4 py-2 text-sm font-medium text-slate-300 hover:text-white">Log in</Link><Link to="/seeker/marketplace" className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950">Explore RAW</Link></div></div></header>
    <main>
      <section className="mx-auto grid max-w-7xl gap-12 px-4 pb-20 pt-16 sm:px-6 lg:grid-cols-[1.2fr_0.8fr] lg:items-center lg:pt-24">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1.5 text-xs font-semibold text-teal-200"><Sparkles className="h-3.5 w-3.5" /> Reuse starts locally</div><h1 className="mt-6 max-w-3xl text-5xl font-black tracking-tight sm:text-6xl lg:text-7xl">Turn surplus into <span className="text-teal-300">value.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">RAW connects reusable and recoverable materials with the people and businesses that can give them a second life.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/seeker/marketplace" className="inline-flex items-center gap-2 rounded-xl bg-teal-300 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-teal-200">Find RAW <ArrowRight className="h-4 w-4" /></Link><Link to="/donor/listings/new" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold hover:bg-white/10">List RAW</Link></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-slate-300"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-teal-300" /> Local matching</div><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-teal-300" /> Smart pricing</div><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-teal-300" /> Verified network</div></div></div>
        <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-3 shadow-2xl shadow-teal-900/10"><img src="/raw-materials-dark.svg" alt="Reusable and recoverable materials" className="h-[330px] w-full rounded-2xl border border-white/10 object-cover object-[65%] sm:h-[420px] lg:h-[500px]" /><div className="pointer-events-none absolute inset-3 rounded-2xl bg-gradient-to-t from-slate-950/10 via-transparent to-transparent" /></div>
      </section>
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><Store className="h-5 w-5 text-teal-300"/><h3 className="mt-4 font-bold">One network for surplus</h3><p className="mt-2 text-sm leading-6 text-slate-400">Sell, donate or swap reusable material with local demand.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><Bot className="h-5 w-5 text-teal-300"/><h3 className="mt-4 font-bold">Explainable RAW Match</h3><p className="mt-2 text-sm leading-6 text-slate-400">See why a supplier or requirement ranks highly before you transact.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><TrendingUp className="h-5 w-5 text-teal-300"/><h3 className="mt-4 font-bold">Impact you can measure</h3><p className="mt-2 text-sm leading-6 text-slate-400">Track material recovered, value recovered and estimated waste avoided.</p></div></div></section>
    </main>
  </div>;
}
